"""Generate data/catalogue.yaml from the training data + the organisers' critical-service list.

Input:  data/jira.json, plus the Critical/Non-Critical ratings from docs/challenge.md.
Output: data/catalogue.yaml — service -> {team, criticality}, and the team roster.
Run:    uv run python scripts/build_catalogue.py   (re-run only if the dataset changes)
Failure mode it prevents: a hand-typed routing table drifting from the data, and routing
being decided by a model instead of a lookup.
"""

import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "jira.json"
OUT = ROOT / "data" / "catalogue.yaml"

# Verbatim from docs/challenge.md (organisers). 14 Critical, 6 Non-Critical.
CRITICAL = {
    "Trading Platform", "Order Management", "Trade Matching", "Securities Settlement",
    "Corporate Actions", "Fund Pricing", "NAV Calculation", "Portfolio Accounting",
    "Cash Management", "Risk & Compliance Monitoring", "Regulatory Reporting",
    "SimCorp Dimension", "Rimes Data Feed", "Client Reporting",
}
NON_CRITICAL = {
    "Tax Reporting", "CRM & Client Portal", "Identity & Access Management",
    "SharePoint & File Storage", "Outlook & Email", "Emailed Support Tickets",
}


def main() -> None:
    rows = json.loads(DATA.read_text(encoding="utf-8"))
    s2t = defaultdict(Counter)
    for r in rows:
        s2t[r["Affected Business or IT Services"][0]][r["Service Team(s)"][0]] += 1

    conflicts = {s: dict(c) for s, c in s2t.items() if len(c) > 1}
    if conflicts:
        raise SystemExit(f"service->team is not 1:1, refusing to write a lookup table: {conflicts}")

    known = CRITICAL | NON_CRITICAL
    if unrated := set(s2t) - known:
        raise SystemExit(f"services with no organiser criticality rating: {sorted(unrated)}")

    lines = [
        "# GENERATED by scripts/build_catalogue.py - do not hand-edit.",
        "# service -> team is 1:1 in the training data (verified, 0 exceptions).",
        "# criticality is the organisers' list from docs/challenge.md, not our invention.",
        "services:",
    ]
    for s in sorted(s2t):
        lines += [
            f"  {json.dumps(s)}:",
            f"    team: {json.dumps(s2t[s].most_common(1)[0][0])}",
            f"    criticality: {'critical' if s in CRITICAL else 'non_critical'}",
        ]

    teams = sorted({c.most_common(1)[0][0] for c in s2t.values()})
    lines.append("teams:")
    lines += [f"  - {json.dumps(t)}" for t in teams]

    # Assignee roster: provably NOT team-specific in this data (all 30 appear under all
    # teams), so we keep one global roster and load-balance within the routed team.
    roster = sorted({r["Assignee"] for r in rows if r.get("Assignee")})
    lines.append("assignees:  # global roster - see README: assignee is unlearnable here")
    lines += [f"  - {json.dumps(a)}" for a in roster]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} : {len(s2t)} services, {len(teams)} teams, {len(roster)} assignees")


if __name__ == "__main__":
    main()
