"""Run the pipeline on a challenge file and write the submission artefacts.

Input : the Jira-export envelope (``{"records": [...]}``), a flat JSON list, or JSONL - either the README's
        ``jira_hackathon_20_new_tickets_challenge.json`` or the shipped ``jira_hackathon_blind_eval_challenge_*.json``.
Output: * predictions JSON  - same envelope/schema as the input, corrected fields filled in, resolution comment appended to
                              ``All Comments`` in the voice of the assignee (training style ``agent@intcom.com: Resolution: ...``)
        * predictions CSV   - flat view incl. the resolution comment, confidence and flags
        * explanations JSON - per-ticket reasons, evidence, agent trace, latency, cost (what makes the answers auditable)

Nothing here looks at ticket identity: the same code path serves any ticket file (README rule: no hardcoded answers).
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

from .config import ROOT, get_settings
from .data import is_envelope, read_records, ticket_from_record
from .models import TriageResult
from .pipeline import Triage


def _case_like(sample: str | None, value: str) -> str:
    return value.capitalize() if sample and sample[:1].isupper() else value


def apply_result(rec: dict, res: TriageResult) -> dict:
    out = dict(rec)
    sample = rec.get("Priority") or rec.get("Urgency") or rec.get("Impact")
    out["Work type"] = res.work_type
    out["Affected Business or IT Services"] = [res.service]
    out["Service Team(s)"] = [res.team]
    out["Assignee"] = res.assignee
    out["Priority"] = _case_like(sample, res.priority)
    out["Urgency"] = _case_like(sample, res.urgency)
    out["Impact"] = _case_like(sample, res.impact)
    out["Resolution"] = res.resolution
    out["Status"] = "done"
    comments = list(rec.get("All Comments") or [])
    if res.assignee and res.resolution_note:
        comments.append(f"{res.assignee}: {res.resolution_note}")
    out["All Comments"] = comments
    return out


def run_challenge(input_path: str | Path, out_dir: str | Path | None = None, use_llm: bool | None = None, tag: str = "") -> dict:
    out_dir = Path(out_dir) if out_dir else get_settings().outputs_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    records, meta = read_records(input_path)
    tickets = [ticket_from_record(r, i, "CH", "jira") for i, r in enumerate(records)]
    tri = Triage(use_llm=use_llm)
    results = tri.run_batch(tickets)

    pred_records = [apply_result(r, res) for r, res in zip(records, results)]
    envelope = {**meta, "records": pred_records} if is_envelope(input_path) else pred_records
    if isinstance(envelope, dict):
        envelope["triagemate"] = {"mode": results[0].mode if results else "offline", "tickets": len(results),
                                  "note": "predictions generated by TriageMate; see explanations file for reasoning"}
    stem = f"challenge_predictions{('_' + tag) if tag else ''}"
    p_json = out_dir / f"{stem}.json"
    p_json.write_text(json.dumps(envelope, indent=2, ensure_ascii=False), encoding="utf-8")

    p_csv = out_dir / f"{stem}.csv"
    with p_csv.open("w", newline="", encoding="utf-8-sig") as f:
        cols = ["ticket_id", "summary", "given_service", "work_type", "service", "team", "assignee", "urgency", "impact", "priority",
                "resolution", "resolution_comment", "confidence", "flags", "resolution_source"]
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for rec, t, r in zip(records, tickets, results):
            w.writerow({"ticket_id": t.id, "summary": t.summary, "given_service": t.service, "work_type": r.work_type, "service": r.service,
                        "team": r.team, "assignee": r.assignee, "urgency": r.urgency, "impact": r.impact, "priority": r.priority,
                        "resolution": r.resolution, "resolution_comment": f"{r.assignee}: {r.resolution_note}", "confidence": r.confidence,
                        "flags": ",".join(k for k, v in r.flags.model_dump().items() if v), "resolution_source": r.resolution_source})

    expl = []
    for t, r in zip(tickets, results):
        expl.append({
            "ticket_id": t.id, "summary": t.summary,
            "given": {"work_type": t.work_type, "service": t.service, "urgency": t.urgency, "impact": t.impact, "priority": t.priority},
            "predicted": {"work_type": r.work_type, "service": r.service, "team": r.team, "assignee": r.assignee,
                          "urgency": r.urgency, "impact": r.impact, "priority": r.priority, "resolution": r.resolution},
            "changed": {"service": r.classification.service_changed, "work_type": r.classification.work_type_changed},
            "why": {"classification": r.classification.reasons, "urgency": r.priority_detail.urgency_reason,
                    "impact": r.priority_detail.impact_reason, "assignee": r.assignee_reason, "resolution_source": r.resolution_source,
                    "notes": r.notes},
            "service_ranking": [{"service": c.service, "score": c.score,
                                 "evidence": [e.detail for e in c.evidence if e.signal in ("strong", "playbook", "prior")][:5]} for c in r.classification.candidates],
            "flags": r.flags.model_dump(), "confidence": r.confidence, "trace": [s.model_dump() for s in r.trace],
            "latency_ms": r.latency_ms, "cost_usd": r.cost_usd, "mode": r.mode,
        })
    p_expl = out_dir / f"challenge_explanations{('_' + tag) if tag else ''}.json"
    p_expl.write_text(json.dumps(expl, indent=2, ensure_ascii=False), encoding="utf-8")

    lat = sorted(r.latency_ms for r in results)
    summary = {
        "tickets": len(results), "mode": results[0].mode if results else "offline",
        "priority_consistent": sum(1 for r in results if r.priority == __import__("triagemate.priority", fromlist=["x"]).matrix_priority(r.urgency, r.impact)),
        "service_changed": sum(1 for r in results if r.classification.service_changed),
        "work_type_changed": sum(1 for r in results if r.classification.work_type_changed),
        "latency_ms_p50": lat[len(lat) // 2] if lat else None, "latency_ms_p95": lat[min(len(lat) - 1, int(0.95 * len(lat)))] if lat else None,
        "mean_cost_usd": round(sum(r.cost_usd for r in results) / max(1, len(results)), 6),
        "files": [str(p_json), str(p_csv), str(p_expl)],
    }
    return summary
